# Generated by Django 5.0.6 on 2024-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketing",
            name="id",
            field=models.DateTimeField(
                auto_now_add=True, primary_key=True, serialize=False
            ),
        ),
    ]
