# Generated by Django 5.0.6 on 2024-07-10 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0002_alter_marketing_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketing",
            name="update_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marketing",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
