# Generated by Django 5.0.6 on 2024-06-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("productId", models.AutoField(primary_key=True, serialize=False)),
                ("productName", models.CharField(max_length=32)),
                ("productLocation", models.CharField(max_length=64)),
                ("productActivity", models.TextField()),
                ("productDining", models.TextField()),
                ("productPrice", models.IntegerField(max_length=10)),
                ("productImageName", models.CharField(max_length=128)),
                ("regDate", models.DateTimeField(auto_now_add=True)),
                ("updDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
