# Generated by Django 5.0.6 on 2024-06-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productPrice",
            field=models.IntegerField(),
        ),
    ]
