# Generated by Django 5.0.6 on 2024-07-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorites",
            fields=[
                ("favoritesId", models.AutoField(primary_key=True, serialize=False)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "db_table": "favorites",
            },
        ),
        migrations.CreateModel(
            name="FavoritesItem",
            fields=[
                (
                    "favoritesItemId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "favorites",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="favorites.favorites",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "favorites_item",
            },
        ),
    ]
